<?php

namespace App\Domain\PPDB\Enums;

enum StatusUtamaPendaftaran: string
{
    case INISIASI = 'INISIASI';
    case PENDAFTARAN_TERKIRIM = 'PENDAFTARAN_TERKIRIM';
    case MENUNGGU_BERKAS_FISIK = 'MENUNGGU_BERKAS_FISIK';
    case BERKAS_FISIK_DITERIMA = 'BERKAS_FISIK_DITERIMA';
    case SEDANG_DIVERIFIKASI = 'SEDANG_DIVERIFIKASI';
    case SIAP_WAWANCARA = 'SIAP_WAWANCARA';
    case WAWANCARA_TERJADWAL = 'WAWANCARA_TERJADWAL';
    case WAWANCARA_SELESAI = 'WAWANCARA_SELESAI';
    case MASUK_PERANGKINGAN = 'MASUK_PERANGKINGAN';
    case HASIL_DITETAPKAN = 'HASIL_DITETAPKAN';
    case GUGUR = 'GUGUR';
    case MENGUNDURKAN_DIRI = 'MENGUNDURKAN_DIRI';
}
